"""empty message

Revision ID: 19a86ff4da17
Revises: c653d9d666c8
Create Date: 2025-06-25 16:39:51.684924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19a86ff4da17'
down_revision = 'c653d9d666c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrollpolicy', schema=None) as batch_op:
        batch_op.alter_column('overtimePolicy',
               existing_type=mysql.ENUM('paid', 'notapplicable'),
               type_=mysql.ENUM('paid', 'compensatory'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrollpolicy', schema=None) as batch_op:
        batch_op.alter_column('overtimePolicy',
               existing_type=mysql.ENUM('paid', 'compensatory'),
               type_=mysql.ENUM('paid', 'notapplicable'),
               existing_nullable=True)

    # ### end Alembic commands ###
