"""empty message

Revision ID: 2e73562649fd
Revises: 575a111ce6aa
Create Date: 2025-06-24 12:27:36.197813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e73562649fd'
down_revision = '575a111ce6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadminpanel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('superadminpanel_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'superadmin', ['superadmin_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadminpanel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('superadminpanel_ibfk_1'), 'superadmin', ['superadmin_id'], ['id'])

    # ### end Alembic commands ###
