"""empty message

Revision ID: 46b06c6bcdcf
Revises: dc68f6f19988
Create Date: 2025-06-25 09:53:31.937573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b06c6bcdcf'
down_revision = 'dc68f6f19988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminassets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iswarranty', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminassets', schema=None) as batch_op:
        batch_op.drop_column('iswarranty')

    # ### end Alembic commands ###
