"""empty message

Revision ID: 4e2e96999aea
Revises: f91e113028b2
Create Date: 2025-06-27 12:04:41.724345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2e96999aea'
down_revision = 'f91e113028b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userticket', schema=None) as batch_op:
        batch_op.drop_column('assigned_by')

    # ### end Alembic commands ###
