"""empty message

Revision ID: 5ddd98746678
Revises: 
Create Date: 2025-06-24 10:33:42.528812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddd98746678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'masteradminpanel', ['master_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('master_id')

    # ### end Alembic commands ###
