"""empty message

Revision ID: 64816444e54e
Revises: 19a86ff4da17
Create Date: 2025-06-25 17:53:33.804548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64816444e54e'
down_revision = '19a86ff4da17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
