"""empty message

Revision ID: 6b013158c4ea
Revises: 46b06c6bcdcf
Create Date: 2025-06-25 11:01:50.292867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b013158c4ea'
down_revision = '46b06c6bcdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useraccess', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('useraccess_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useraccess', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('useraccess_ibfk_1'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
