"""empty message

Revision ID: 830a2dc08429
Revises: 4e2e96999aea
Create Date: 2025-06-27 16:06:14.210422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830a2dc08429'
down_revision = '4e2e96999aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branchcreation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('branchcreation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'superadminpanel', ['superpanel'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branchcreation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('branchcreation_ibfk_1'), 'superadmin', ['superpanel'], ['id'])

    # ### end Alembic commands ###
