"""empty message

Revision ID: a506853b9efa
Revises: 1fb98f2c9e9e
Create Date: 2025-06-26 11:15:49.796452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a506853b9efa'
down_revision = '1fb98f2c9e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('recieverID',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('recieverID',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
