"""empty message

Revision ID: c653d9d666c8
Revises: 6b013158c4ea
Create Date: 2025-06-25 12:30:33.100803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c653d9d666c8'
down_revision = '6b013158c4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.alter_column('leaveType',
               existing_type=mysql.ENUM('casual', 'sick'),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.alter_column('leaveType',
               existing_type=sa.String(length=120),
               type_=mysql.ENUM('casual', 'sick'),
               existing_nullable=False)

    # ### end Alembic commands ###
