"""empty message

Revision ID: dc68f6f19988
Revises: 7aecb95ad560
Create Date: 2025-06-25 08:05:03.428037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc68f6f19988'
down_revision = '7aecb95ad560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
