"""empty message

Revision ID: f91e113028b2
Revises: a506853b9efa
Create Date: 2025-06-26 17:43:34.964872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91e113028b2'
down_revision = 'a506853b9efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskmanagement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskmanagement', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
